/oakd:
  ros__parameters:
    camera:
      i_enable_ir: true
      i_nn_type: none
      i_pipeline_type: 'Stereo'
      i_usb_speed: SUPER_PLUS
      i_tf_camera_model: 'OAK-D-LITE'
      i_tf_camera_name: 'oak'
      i_tf_parent_frame: 'oak-d-base-frame'
    pipeline_gen:
      i_enable_imu: false
      i_enable_diagnostics: false
    left:
      i_publish_topic: false
    right:
      i_publish_topic: true
      i_low_bandwidth: true
      i_low_bandwidth_quality: 25
      i_publish_compressed: true
      i_resolution: '480P'
      i_width: 320
      i_height: 240
      i_fps: 5.0
      i_max_q_size: 4
    stereo:
      i_publish_topic: false
    use_sim_time: false
